# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  only:
    - master

# Build worker image (VM template)
image: Visual Studio 2013

# environment variables
environment:
  mxnet_variant: CPU
    # - mxnet_variant: MKL
    # - mxnet_variant: CU75
    # - mxnet_variant: CU80
    # - mxnet_variant: CU75MKL
    # - mxnet_variant: CU80MKL
  TARGET_ARCH:
    - "32"
    - "64"
  PYTHON: Python34
  DEPENDENCIES_DIR: C:\deps

matrix:
  fast_finish: true

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - mkdir %DEPENDENCIES_DIR%
  - call .\windows\init.cmd

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\deps\opencv-install -> windows/make_opencv.cmd
  - C:\deps\openblas-install -> windows/make_openblas.cmd

# scripts that run after cloning repository
install:
  - call .\windows\install.cmd

# real work
build:

# scripts to run before build
before_build:
  - call ./windows/before_build.cmd

# scripts to run after build
after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - call %PYTHON_EXE% setup.py bdist_wheel

# to run your custom scripts instead of automatic MSBuild
build_script:
  # in mxnet-build\build
  - cmake --build . --config Release --target ALL_BUILD

# scripts to run before tests
before_test:
  - cd %APPVEYOR_BUILD_FOLDER%
  - FOR /F "tokens=* USEBACKQ" %%F IN (`dir /b /a-d dist\mxnet*`) DO (SET wheel_name=%%F)

# to run your custom scripts instead of automatic tests
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo %wheel_name%
  - 7z x "dist\%wheel_name%" -odebug_wheel
  - dir
  - dir debug_wheel\mxnet
  - call %PIP_EXE% -U --force-reinstall "dist\%wheel_name%"
  - call %PYTHON_EXE% sanity_test.py
  - call %NOSE_EXE% -v mxnet-build\tests\python\unittest\test_gluon.py
