# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  only:
    - master

# Build worker image (VM template)
image: Visual Studio 2015

# environment variables
environment:
  matrix:
    - mxnet_variant: CPU
      TARGET_ARCH: 64
    - mxnet_variant: CPU
      TARGET_ARCH: 32

    # - mxnet_variant: MKL
    # - mxnet_variant: CU75
    # - mxnet_variant: CU80
    # - mxnet_variant: CU75MKL
    # - mxnet_variant: CU80MKL
  PYTHON: Python35
  DEPENDENCIES_DIR: C:\deps
  PYPI_PASSWORD:
    secure: I2X8n7lRmasNOSfkam/LctMp5yw2X3UYmsA46RD6ikI=
  PYPI_USERNAME:
    secure: aOj5+o65rCsGgeSwL7nHjg==

matrix:
  fast_finish: true

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - mkdir %DEPENDENCIES_DIR%
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" ) { write-output "From a tag build"; $GIT_TAG = (echo $env:APPVEYOR_REPO_TAG_NAME | %{$_ -replace "^patch-[^-]*-", ""});  $env:GIT_ADDITIONAL_FLAGS = "-b $GIT_TAG"; write-output $env:GIT_ADDITIONAL_FLAGS} Else { write-output "Not from a tag build"}
  - ps: If ($env:APPVEYOR_SCHEDULED_BUILD -eq "True" ) { write-output "From a scheduled build" } Else { write-output "Not from a scheduled build"}

# cache:
  # - C:\ProgramData\chocolatey\bin -> appveyor.yml
  # - C:\ProgramData\chocolatey\lib -> appveyor.yml
  # - C:\deps\opencv-install -> windows/make_opencv.cmd
  # - C:\deps\openblas-install -> windows/make_openblas.cmd

# scripts that run after cloning repository
install:
  - echo "install script"
  - call .\windows\init.cmd
  - call .\windows\install.cmd

# real work
build:

# scripts to run before build
before_build:
  - echo "before build script"
  - call .\windows\before_build.cmd

# scripts to run after build
after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - call %PYTHON_EXE% setup.py bdist_wheel

# to run your custom scripts instead of automatic MSBuild
build_script:
  # in mxnet-build\build
  - cmake --build . --config Release --target ALL_BUILD -- /m:2

# scripts to run before tests
before_test:
  - cd %APPVEYOR_BUILD_FOLDER%
  - FOR /F "tokens=* USEBACKQ" %%F IN (`dir /b /a-d dist\mxnet*`) DO (SET wheel_name=%%F)

# to run your custom scripts instead of automatic tests
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo %wheel_name%
  - 7z x "dist\%wheel_name%" -odebug_wheel
  - dir
  - dir debug_wheel\mxnet
  - call %PIP_EXE% install -U --force-reinstall "dist\%wheel_name%"
  - call %PYTHON_EXE% sanity_test.py
  - call %NOSE_EXE% -v mxnet-build\tests\python\unittest\test_gluon.py
  # - call %NOSE_EXE% -v mxnet-build\tests\python\unittest\test_gluon_data.py
  # - call %NOSE_EXE% -v mxnet-build\tests\python\unittest\test_gluon_model_zoo.py

artifacts:
  - path: dist\*
    name: pypiartifacts

deploy_script:
  # - call %TWINE_EXE% upload -r legacy --skip-existing dist/*
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" -Or $env:APPVEYOR_SCHEDULED_BUILD -eq "True") { Invoke-Expression "$env:TWINE_EXE upload -r legacy --skip-existing dist/*" } Else { write-output "Not on a tag or scheduled, won't deploy to pypi"}
