# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input


# environment variables
environment:
  BUILD_TARGET_PLATFORM: Visual Studio 14 2015 Win64

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

# build cache to preserve files/folders between builds
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\deps\opencv\build\install -> windows/make_opencv.cmd
  - C:\deps\openblas -> windows/make_openblas.cmd

# scripts that run after cloning repository
install:
  - call ./windows/make_openblas.cmd
  - call ./windows/make_opencv.cmd
  # cmake
  - call ./windows/choco_install.cmd

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:

# scripts to run before build
before_build:

  - git clone --recursive https://github.com/apache/incubator-mxnet mxnet-build
  - cd .\mxnet-build
  - mkdir build
  - cd .\build
  - set OpenBLAS_HOME=c:\deps\openblas
  - set OpenCV_DIR=c:\deps\opencv\build\install
  - cmake .. -DOPENCV_DIR=%OpenCV_DIR% -DUSE_PROFILER=1 -DUSE_CUDA=0 -DUSE_CUDNN=0 -DUSE_NVRTC=0 -DUSE_OPENCV=1 -DUSE_OPENMP=1 -DUSE_BLAS=open -DUSE_LAPACK=1 -DUSE_DIST_KVSTORE=0 -DCMAKE_BUILD_TYPE=Release -G "%BUILD_TARGET_PLATFORM%"

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - pip install pypandoc
  - set mxnet_variant=CPU
  - python setup.py bdist_wheel

# to run your custom scripts instead of automatic MSBuild
build_script:
  - msbuild mxnet.sln /t:Rebuild /p:Configuration=Release;Platform=x64 /m

# to disable automatic builds
#build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run tests again only selected assemblies and/or categories
#test:


# scripts to run before tests
before_test:
  - cd %APPVEYOR_BUILD_FOLDER%
  - python platform_test.py
  - cd %APPVEYOR_BUILD_FOLDER%/dist
  - FOR /F "tokens=* USEBACKQ" %%F IN (`dir /b /a-d mxnet*`) DO (SET wheel_name=%%F)
  - pip install -U --force-reinstall %wheel_name%

# scripts to run after tests
after_test:

# to run your custom scripts instead of automatic tests
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - python sanity_test.py

# to disable automatic tests
#test: off
