# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# environment variables
environment:
  BUILD_TARGET_PLATFORM: Visual Studio 14 2015 Win64
  mxnet_variant: CPU
  PYTHON: C:\Python36-x64
  PYTHON_VERSION: "3.6.1"
  PYTHON_ARCH: "64"

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

# build cache to preserve files/folders between builds
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\deps\opencv\build\install -> windows/make_opencv.cmd
  - C:\deps\openblas -> windows/make_openblas.cmd

# scripts that run after cloning repository
install:
  - %PYTHON%/python --version
  - "%PYTHON%/Scripts/pip --version"
  - call ./windows/make_openblas.cmd
  - call ./windows/make_opencv.cmd
  - call ./windows/choco_install.cmd

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:

# scripts to run before build
before_build:
  - call ./windows/before_build.cmd

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%PYTHON%/Scripts/pip install pypandoc"
  - "%PYTHON%/python -c 'import pypandoc'"
  - "%PYTHON%/python setup.py bdist_wheel"

# to run your custom scripts instead of automatic MSBuild
build_script:
  - msbuild mxnet.sln /t:Rebuild /p:Configuration=Release;Platform=x64 /m

# to disable automatic builds
#build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run tests again only selected assemblies and/or categories
#test:


# scripts to run before tests
before_test:
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%PYTHON%/python -c 'import pip; print(pip.pep425tags.get_supported())'"
  - FOR /F "tokens=* USEBACKQ" %%F IN (`dir /b /a-d dir\mxnet*`) DO (SET wheel_name=%%F)

# scripts to run after tests
after_test:

# to run your custom scripts instead of automatic tests
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - 7z x "%wheel_name%" -odebug_wheel
  - dir
  - dir debug_wheel\mxnet
  - "%PYTHON%/Scripts/pip install -U --force-reinstall %wheel_name% || exit 0"
  - "%PYTHON%/python sanity_test.py"

# to disable automatic tests
#test: off
